name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit

      - name: Execute Gradle build
        run: ./gradlew build

  review:
    if: github.event_name == 'pull_request'
    needs: gradle
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: true
